// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9H4IFPYPUQKEmprVmtVAp7CbBCU6H7BI',
    appId: '1:957917582557:web:0fda3766bd494300867734',
    messagingSenderId: '957917582557',
    projectId: 'final-app-3b2b8',
    authDomain: 'final-app-3b2b8.firebaseapp.com',
    storageBucket: 'final-app-3b2b8.firebasestorage.app',
    measurementId: 'G-Y7MMX6MR11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbbG8DHxB1tlcvCFSHaAPdL3IWTYw9EQ',
    appId: '1:957917582557:android:5850f871bbe549a1867734',
    messagingSenderId: '957917582557',
    projectId: 'final-app-3b2b8',
    storageBucket: 'final-app-3b2b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFFfbjEqwvWeJuHpyGU-j_6sUnLo2VAs',
    appId: '1:957917582557:ios:8ea2b81bcbe36648867734',
    messagingSenderId: '957917582557',
    projectId: 'final-app-3b2b8',
    storageBucket: 'final-app-3b2b8.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsFFfbjEqwvWeJuHpyGU-j_6sUnLo2VAs',
    appId: '1:957917582557:ios:8ea2b81bcbe36648867734',
    messagingSenderId: '957917582557',
    projectId: 'final-app-3b2b8',
    storageBucket: 'final-app-3b2b8.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9H4IFPYPUQKEmprVmtVAp7CbBCU6H7BI',
    appId: '1:957917582557:web:61cb1ff7d7d9acf3867734',
    messagingSenderId: '957917582557',
    projectId: 'final-app-3b2b8',
    authDomain: 'final-app-3b2b8.firebaseapp.com',
    storageBucket: 'final-app-3b2b8.firebasestorage.app',
    measurementId: 'G-SZ0GJHK8QC',
  );

}